import { getProviders, signIn as signInProvider } from "next-auth/react";
import Head from "next/head";
import Header from "../../components/Header";

const SignIn = ({ providers }) => {
  return (
    <div className='bg-slate-200 h-screen'>
      <Head>
        <title>Newstagram - Sign In</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />

      <h1 className='capitalize'>sign in page</h1>

      {/* iniciar sesion */}
      <div>
        {Object.values(providers).map((provider) => (
          <div key={provider.name}>
            <button
              className='hover:bg-red-300 p-3 rounded-md border-2 border-red-300 hover:text-white font-bold transition-all duration-200 ease-in'
              onClick={() => signInProvider(provider.id)}>
              Sign in with {provider.name}
            </button>
          </div>
        ))}
      </div>
    </div>
  );
};

export async function getServerSideProps() {
  const providers = await getProviders();

  return { props: { providers } };
}

export default SignIn;
