import Head from "next/head";
import Feed from "../components/Feed";
import Header from "../components/Header";

export default function Home() {
  return (
    <div className='bg-slate-100 dark:bg-gradient-to-t dark:from-slate-300 dark:to-slate-600 h-screen overflow-y-scroll'>
      <Head>
        <title>Newstagram</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* header */}
      <Header />

      {/* feed */}
      <Feed />

      {/* modal */}
    </div>
  );
}
