import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import Feed from "../components/Feed";
import Header from "../components/Header";
import { useSession } from "next-auth/react";

export default function Home() {
  const router = useRouter();
  const { data: session } = useSession();

  useEffect(() => {
    if (session === null) {
      router.push("/auth/signin");
      return;
    }
  });
  return (
    <>
      {session && (
        <div className='bg-slate-200 h-screen overflow-y-scroll'>
          <Head>
            <title>Newstagram</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
          </Head>

          <Header />

          <Feed />

          {/* modal */}
        </div>
      )}
    </>
  );
}
